# -----------------------------------
# -------- OPENOCD SERVER -----------
# -----------------------------------

FROM ubuntu:22.04 as base

# Install dependencies
RUN apt-get update && apt-get install -y \
    openocd

# Expose port
EXPOSE 4444

# Start OpenOCD server
CMD openocd \
    -f interface/stlink.cfg \
    -f target/nrf51.cfg
